import type { Metadata } from "next"
import { Inter, Rubik } from "next/font/google"
import "./globals.css"
import { ViewTransitions } from "next-view-transitions"
import { Toaster } from "@/components/ui/toaster"

const rubik = Rubik({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ViewTransitions>
      <html lang="en" suppressHydrationWarning>
        <body className={rubik.className}>
          <main className="p-2 scroll-smooth">{children}</main>
          <Toaster />
        </body>
      </html>
    </ViewTransitions>
  )
}
